///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostAbsen {
/*
{
  "tipe_absen": "1",
  "datang_pulang": "out",
  "wfh_wfo": "wfh",
  "tanggal_absen": "2021-08-09",
  "jam_absen": "02:54:02",
  "lokasi": "Jalan PU 35, Cimuning, Kecamatan Mustika Jaya, Kota Bekasi, Jawa Barat 17154, Indonesia",
  "latitude": "-6.34",
  "longitude": "107.020889",
  "keterangan": null
} 
*/

  String? tipe_absen;
  String? datang_pulang;
  String? wfh_wfo;
  String? tanggal_absen;
  String? jam_absen;
  String? lokasi;
  String? latitude;
  String? longitude;
  String? keterangan;

  PostAbsen({
    this.tipe_absen,
    this.datang_pulang,
    this.wfh_wfo,
    this.tanggal_absen,
    this.jam_absen,
    this.lokasi,
    this.latitude,
    this.longitude,
    this.keterangan,
  });
  PostAbsen.fromJson(Map<String, dynamic> json) {
    tipe_absen = json["tipe_absen"]?.toString();
    datang_pulang = json["datang_pulang"]?.toString();
    wfh_wfo = json["wfh_wfo"]?.toString();
    tanggal_absen = json["tanggal_absen"]?.toString();
    jam_absen = json["jam_absen"]?.toString();
    lokasi = json["lokasi"]?.toString();
    latitude = json["latitude"]?.toString();
    longitude = json["longitude"]?.toString();
    keterangan = json["keterangan"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["tipe_absen"] = tipe_absen;
    data["datang_pulang"] = datang_pulang;
    data["wfh_wfo"] = wfh_wfo;
    data["tanggal_absen"] = tanggal_absen;
    data["jam_absen"] = jam_absen;
    data["lokasi"] = lokasi;
    data["latitude"] = latitude;
    data["longitude"] = longitude;
    data["keterangan"] = keterangan;
    return data;
  }
}
