///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostLogin {
/*
{
  "username": "satrio@gmail.com",
  "password": "123456"
} 
*/

  String? username;
  String? password;

  PostLogin({
    this.username,
    this.password,
  });
  PostLogin.fromJson(Map<String, dynamic> json) {
    username = json["username"]?.toString();
    password = json["password"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["username"] = username;
    data["password"] = password;
    return data;
  }
}
