///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReturnLoginDataUser {
/*
{
  "user_id": "1",
  "username": "superadmin",
  "email": "superadmin@admin.com",
  "staff_id": "1",
  "nik": null,
  "first_name": "Ayu",
  "last_name": "Finance",
  "phone": "8777123455",
  "address": "JAKARTA",
  "birth_place": "Jakarta",
  "birth_day": "1999-06-11",
  "position": null,
  "section": "Manager Human Resources",
  "division": null,
  "facedata": null,
  "jarak": 500,
  "latitude": -6.2693946,
  "longitude": 106.8158465,
  "date": "20210901134346"
} 
*/

  String? userId;
  String? username;
  String? email;
  String? staffId;
  String? nik;
  String? firstName;
  String? lastName;
  String? phone;
  String? address;
  String? birthPlace;
  String? birthDay;
  String? position;
  String? section;
  String? division;
  String? facedata;
  String? radius;
  String? latitude;
  String? longitude;
  String? date;

  ReturnLoginDataUser({
    this.userId,
    this.username,
    this.email,
    this.staffId,
    this.nik,
    this.firstName,
    this.lastName,
    this.phone,
    this.address,
    this.birthPlace,
    this.birthDay,
    this.position,
    this.section,
    this.division,
    this.facedata,
    this.radius,
    this.latitude,
    this.longitude,
    this.date,
  });
  ReturnLoginDataUser.fromJson(Map<String, dynamic> json) {
    userId = json["user_id"]?.toString();
    username = json["username"]?.toString();
    email = json["email"]?.toString();
    staffId = json["staff_id"]?.toString();
    nik = json["nik"]?.toString();
    firstName = json["first_name"]?.toString();
    lastName = json["last_name"]?.toString();
    phone = json["phone"]?.toString();
    address = json["address"]?.toString();
    birthPlace = json["birth_place"]?.toString();
    birthDay = json["birth_day"]?.toString();
    position = json["position"]?.toString();
    section = json["section"]?.toString();
    division = json["division"]?.toString();
    facedata = json["facedata"]?.toString();
    radius = json["radius"]?.toString();
    latitude = json["latitude"]?.toString();
    longitude = json["longitude"]?.toString();
    date = json["date"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["user_id"] = userId;
    data["username"] = username;
    data["email"] = email;
    data["staff_id"] = staffId;
    data["nik"] = nik;
    data["first_name"] = firstName;
    data["last_name"] = lastName;
    data["phone"] = phone;
    data["address"] = address;
    data["birth_place"] = birthPlace;
    data["birth_day"] = birthDay;
    data["position"] = position;
    data["section"] = section;
    data["division"] = division;
    data["facedata"] = facedata;
    data["radius"] = radius;
    data["latitude"] = latitude;
    data["longitude"] = longitude;
    data["date"] = date;
    return data;
  }
}

class ReturnLogin {
/*
{
  "status_json": true,
  "remarks": "Successfully Login Into System",
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMSJ9.X0U0LvE84g8VNkO0_RW7Gjti2Sf1D90B-gvz3zyLIvI",
  "data_user": {
    "user_id": "1",
    "username": "superadmin",
    "email": "superadmin@admin.com",
    "staff_id": "1",
    "nik": null,
    "first_name": "Ayu",
    "last_name": "Finance",
    "phone": "8777123455",
    "address": "JAKARTA",
    "birth_place": "Jakarta",
    "birth_day": "1999-06-11",
    "position": null,
    "section": "Manager Human Resources",
    "division": null,
    "facedata": null,
    "jarak": 500,
    "latitude": -6.2693946,
    "longitude": 106.8158465,
    "date": "20210901134346"
  }
} 
*/

  bool? statusJson;
  String? remarks;
  String? token;
  ReturnLoginDataUser? dataUser;

  ReturnLogin({
    this.statusJson,
    this.remarks,
    this.token,
    this.dataUser,
  });
  ReturnLogin.fromJson(Map<String, dynamic> json) {
    statusJson = json["status_json"];
    remarks = json["remarks"]?.toString();
    token = json["token"]?.toString();
    dataUser = (json["data_user"] != null)
        ? ReturnLoginDataUser.fromJson(json["data_user"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status_json"] = statusJson;
    data["remarks"] = remarks;
    data["token"] = token;
    if (dataUser != null) {
      data["data_user"] = dataUser!.toJson();
    }
    return data;
  }
}
